-- Create tables
CREATE TABLE IF NOT EXISTS projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  tags TEXT[],
  github_url TEXT,
  demo_url TEXT,
  user_id UUID REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  published BOOLEAN DEFAULT false,
  image_url TEXT,
  excerpt TEXT
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  site_title TEXT NOT NULL DEFAULT 'My Portfolio',
  site_description TEXT NOT NULL DEFAULT 'Welcome to my portfolio',
  contact_email TEXT NOT NULL DEFAULT '',
  social_links JSONB DEFAULT '{}'::jsonb
);

-- Enable RLS
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Projects Policies
CREATE POLICY "Public projects are viewable by everyone" 
ON projects FOR SELECT 
USING (true);

CREATE POLICY "Admins can insert projects" 
ON projects FOR INSERT 
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can update projects" 
ON projects FOR UPDATE 
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can delete projects" 
ON projects FOR DELETE 
USING (auth.uid() IS NOT NULL);

-- Posts Policies
CREATE POLICY "Published posts are viewable by everyone" 
ON posts FOR SELECT 
USING (published = true);

CREATE POLICY "Admins can view all posts" 
ON posts FOR SELECT 
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can insert posts" 
ON posts FOR INSERT 
WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can update posts" 
ON posts FOR UPDATE 
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can delete posts" 
ON posts FOR DELETE 
USING (auth.uid() IS NOT NULL);

-- Contact Messages Policies
CREATE POLICY "Anyone can send messages" 
ON contact_messages FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Admins can view messages" 
ON contact_messages FOR SELECT 
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can update messages (mark as read)" 
ON contact_messages FOR UPDATE 
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can delete messages" 
ON contact_messages FOR DELETE 
USING (auth.uid() IS NOT NULL);

-- Settings Policies
CREATE POLICY "Settings are viewable by everyone" 
ON settings FOR SELECT 
USING (true);

CREATE POLICY "Admins can update settings" 
ON settings FOR UPDATE 
USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can insert settings" 
ON settings FOR INSERT 
WITH CHECK (auth.uid() IS NOT NULL);

-- Create Storage Bucket for Images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Auth users can upload" ON storage.objects;

-- Create storage policies
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'images' );

CREATE POLICY "Auth users can upload" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'images' AND auth.role() = 'authenticated' );
